
CC = g++
CPPFLAGS = -std=c++11 -Wall #-Wextra



MergeSort:
	${CC} ${CPPFLAGS} MergeSort.cpp -o MergeSort

QuickSort:
	${CC} ${CPPFLAGS} QuickSort.cpp -o QuickSort



clean:
	rm -f MergeSort QuickSort

new:
	make clean MergeSort


