
CC = g++
CPPFLAGS = -std=c++11 -Wall #-Wextra



MergeSort:
	${CC} ${CPPFLAGS} MergeSort.cpp -o MergeSort

QuickSort:
	${CC} ${CPPFLAGS} QuickSort.cpp -o QuickSort

InsertionSort:
	${CC} ${CPPFLAGS} InsertionSort.cpp -o InsertionSort

clean:
	rm -f MergeSort QuickSort InsertionSort

new:
	make clean MergeSort QuickSort InsertionSort


